"""Real-time MIDI session recorder to export human-machine improvisations for analysis and DAW playback."""

import logging
import os
import time
from typing import List, Tuple
import mido

logger = logging.getLogger("MelodictRecorder")


class SessionRecorder:
    """Records human inputs and machine continuations into a standardized multi-track MIDI file."""

    def __init__(self, output_dir: str = "recordings") -> None:
        """
        Initialize the session recorder.
        
        Args:
            output_dir: Directory where the generated .mid files will be saved.
        """
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)
        
        self.start_time = time.time()
        # Track events stored as tuples: (timestamp_seconds, track_name, midi_note, velocity, duration_sec)
        self.events: List[Tuple[float, str, int, int, float]] = []
        self.is_recording = True

    def log_event(self, track_name: str, midi_note: int, velocity: int = 100, duration: float = 0.3) -> None:
        """
        Log a single note event with its absolute timestamp.
        
        Args:
            track_name: Identifier for the track ('Musician' or 'Melodict_AI').
            midi_note: Symbolic MIDI pitch (21-108).
            velocity: Note intensity (0-127).
            duration: Note duration in seconds.
        """
        if not self.is_recording or midi_note <= 0:
            return
        
        elapsed = time.time() - self.start_time
        self.events.append((elapsed, track_name, midi_note, velocity, duration))
        logger.debug(f"Logged event [{track_name}]: MIDI {midi_note} at {elapsed:.2f}s")

    def log_phrase(self, track_name: str, phrase: List[int], note_duration: float = 0.25) -> None:
        """Log a complete sequence of notes generated by the AI continuation engine."""
        for i, note in enumerate(phrase):
            # Offset each note sequentially in time so they play as a melody, not a simultaneous chord
            elapsed = (time.time() - self.start_time) + (i * note_duration)
            self.events.append((elapsed, track_name, note, 100, note_duration))

    def export_midi_file(self, filename: str = "last_session.mid") -> str:
        """
        Compile the logged timestamps into a multi-track MIDI file (Track 1: Musician, Track 2: AI).
        
        Returns:
            Absolute path to the exported MIDI file.
        """
        if not self.events:
            logger.warning("No musical events recorded. Skipping export.")
            return ""

        mid = mido.MidiFile(type=1)  # Type 1 = multi-track synchronous
        ticks_per_beat = mid.ticks_per_beat
        # Assume 120 BPM for standard real-time conversion (500ms per beat / 1 tick ~ 1.04ms)
        sec_to_ticks = lambda sec: int((sec / 0.5) * ticks_per_beat)

        tracks_data = {"Musician": mido.MidiTrack(), "Melodict_AI": mido.MidiTrack()}
        for name, track in tracks_data.items():
            mid.tracks.append(track)
            track.append(mido.MetaMessage("track_name", name=name, time=0))
            # Set instruments (General MIDI): Musician = Vibraphone (11), AI = Acoustic Grand Piano (0)
            program = 11 if name == "Musician" else 0
            track.append(mido.Message("program_change", program=program, time=0))

        # Separate and sort events per track by start time
        for target_track in ["Musician", "Melodict_AI"]:
            track_events = [e for e in self.events if e[1] == target_track]
            track_events.sort(key=lambda x: x[0])  # Sort by timestamp
            
            midi_track = tracks_data[target_track]
            last_tick = 0
            
            # Create explicit note_on and note_off messages
            raw_messages = []
            for start_sec, _, note, vel, dur in track_events:
                start_tick = sec_to_ticks(start_sec)
                end_tick = sec_to_ticks(start_sec + dur)
                raw_messages.append((start_tick, "note_on", note, vel))
                raw_messages.append((end_tick, "note_off", note, 0))
                
            raw_messages.sort(key=lambda x: (x[0], x[1] == "note_on"))
            
            # Convert absolute ticks to relative delta-times required by MIDI specifications
            for abs_tick, msg_type, note, vel in raw_messages:
                delta_time = max(0, abs_tick - last_tick)
                midi_track.append(mido.Message(msg_type, note=note, velocity=vel, time=delta_time))
                last_tick = abs_tick

        filepath = os.path.join(self.output_dir, filename)
        mid.save(filepath)
        logger.info(f"Session successfully exported to: {filepath}")
        return filepath