"""Simulate an interactive call-and-response jazz session using the VMM Continuator."""

import time

from melodict.generation.continuator import VMMContinuator

NoteTuple = tuple[int, int, int]


def to_note_tuples(pitches: list[int], duration: int = 250, velocity: int = 100) -> list[NoteTuple]:
    """Helper function to convert a list of simple pitches into proper NoteTuples."""
    return [(p, duration, velocity) for p in pitches]


def run_call_and_response_demo() -> None:
    """Simulate feeding jazz vocabulary to the Continuator and testing its reactive responses."""
    print("\n--- Melodict VMM Continuator Call-and-Response Test ---")
    
    # 1. Initialize the Continuator (looking back up to 4 notes for context)
    continuator = VMMContinuator(max_order=4)
    
    # 2. Feed a mini-corpus of standard jazz vocabulary (e.g., ii-V-I licks in C major / A minor)
    jazz_corpus_pitches = [
        [62, 65, 67, 69, 67, 64, 60],  # Dm7 -> G7 -> Cmaj7 phrasing
        [60, 62, 64, 67, 69, 72, 71],  # Ascending pentatonic run
        [72, 71, 69, 67, 65, 64, 62],  # Descending bebop scale fragment
        [67, 69, 67, 65, 64, 62, 60],  # Bluesy turnaround
        [62, 65, 67, 69, 72, 74, 76],  # High register extension
    ]
    
    print("Training VMM Continuator on foundational jazz phrasing corpus...")
    
    # Mock the dictionary structure generated by PhraseBuilder
    mock_dictionary: dict[int, list[list[NoteTuple]]] = {}
    for pitches in jazz_corpus_pitches:
        phrase = to_note_tuples(pitches)
        mock_dictionary.setdefault(len(phrase), []).append(phrase)
        
    continuator.learn_from_dictionary(mock_dictionary)
    
    # Calculate transitions learned
    vocab_size = sum(len(v) for v in continuator.transitions.values())
    print(f"Training complete. Vocabulary transitions learned: {vocab_size}.\n")
    print("-" * 65)
    
    # 3. Simulate real-time prompts played by the musician
    test_prompts = [
        ("Musician plays ascending opening", [60, 62, 64, 67]),
        ("Musician plays turnaround lick", [69, 67, 65, 64]),
        ("Musician plays short high call", [72, 74]),
    ]
    
    for label, prompt_pitches in test_prompts:
        print(f"\nPROMPT: {label}")
        print(f"  -> Input MIDI Sequence: {prompt_pitches}")
        
        prompt_tuples = to_note_tuples(prompt_pitches)
        
        start_time = time.perf_counter()
        # Generate an answer matching the length of the prompt
        answer_tuples = continuator.generate_continuation(input_phrase=prompt_tuples, target_length=5, temperature=0.6)
        calc_time_ms = (time.perf_counter() - start_time) * 1000.0
        
        # Extract just the pitches for clean printing
        answer_pitches = [p for p, d, v in answer_tuples]
        
        print(f"  <- AI Answer Sequence : {answer_pitches}")
        print(f"     [Generation Latency: {calc_time_ms:.3f} ms | Backoff Context Applied]")
        
        # Learn from the musician's prompt on-the-fly to expand the vocabulary
        mock_prompt_dict = {len(prompt_tuples): [prompt_tuples]}
        continuator.learn_from_dictionary(mock_prompt_dict)
        
    print("\n" + "-" * 65 + "\n")


if __name__ == "__main__":
    run_call_and_response_demo()