"""Variable-order Markov Model (VMM) for real-time melodic continuation and reactive call-and-response."""

import logging
import random
from collections import defaultdict
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger("MelodictContinuator")


class VMMContinuator:
    """
    Implements a Variable-order Markov Model with backoff smoothing.
    Learns symbolic melodic phrasing on-the-fly and generates stylistic continuations.
    """

    def __init__(self, max_order: int = 4) -> None:
        """
        Initialize the VMM Continuator.
        
        Args:
            max_order: Maximum prefix length (context size) to look back when generating next notes.
        """
        self.max_order = max_order
        # Transition tree: maps a prefix tuple of notes to a list of observed candidate next notes
        self.transitions: Dict[Tuple[int, ...], List[int]] = defaultdict(list)
        # Vocabulary of all unique MIDI notes seen so far
        self.vocabulary: set = set()
        self.total_notes_learned: int = 0

    def learn_phrase(self, phrase: List[int]) -> None:
        """
        Incorporate a new melodic phrase into the transition tree across all variable orders.
        
        Args:
            phrase: Sequence of symbolic MIDI note numbers.
        """
        if len(phrase) < 2:
            return

        for note in phrase:
            self.vocabulary.add(note)
            self.total_notes_learned += 1

        # Build n-gram prefixes from order 1 up to max_order
        for order in range(1, self.max_order + 1):
            for i in range(len(phrase) - order):
                prefix = tuple(phrase[i : i + order])
                next_note = phrase[i + order]
                self.transitions[prefix].append(next_note)

        logger.debug(f"Learned phrase of length {len(phrase)}. Total tree nodes: {len(self.transitions)}")

    def learn_from_dictionary(self, phrase_dict: Dict[int, List[List[int]]]) -> None:
        """Batch learn from a dictionary generated by the PhraseBuilder."""
        count = 0
        for length, phrases in phrase_dict.items():
            for phrase in phrases:
                self.learn_phrase(phrase)
                count += 1
        logger.info(f"Continuator successfully indexed {count} phrases into VMM tree.")

    def _get_next_candidate(self, current_context: List[int], temperature: float = 1.0) -> Optional[int]:
        """
        Predict the next single note using longest-matching prefix backoff.
        
        Args:
            current_context: Recent history of generated or input notes.
            temperature: Randomness factor (0.0 = deterministic/most frequent, 1.0 = proportional sampling).
        """
        if not self.vocabulary:
            return None

        # Try longest context first, backing off down to order 1
        for order in range(min(self.max_order, len(current_context)), 0, -1):
            prefix = tuple(current_context[-order:])
            candidates = self.transitions.get(prefix)
            
            if candidates:
                if temperature <= 0.1:
                    # Deterministic mode: return the most frequent continuation for this prefix
                    return max(set(candidates), key=candidates.count)
                else:
                    # Probabilistic mode: sample from empirical distribution
                    return random.choice(candidates)

        # Fallback (Order 0): If no matching prefix is found, sample from the entire known vocabulary
        return random.choice(list(self.vocabulary))

    def generate_continuation(
        self, input_phrase: List[int], target_length: Optional[int] = None, temperature: float = 0.8
    ) -> List[int]:
        """
        Generate a melodic response that seamlessly continues the input phrase.
        
        Args:
            input_phrase: The phrase just played by the musician (used to seed the continuation).
            target_length: Number of notes to generate. If None, matches the input phrase length.
            temperature: Creativity/randomness setting for the continuation.
            
        Returns:
            List of generated MIDI note numbers representing the machine's answer.
        """
        if not input_phrase or not self.vocabulary:
            return []

        if target_length is None:
            target_length = max(3, len(input_phrase))

        # Seed the context with the end of the musician's phrase
        context = list(input_phrase)
        generated_response: List[int] = []

        for _ in range(target_length):
            next_note = self._get_next_candidate(context, temperature=temperature)
            if next_note is None:
                break
            generated_response.append(next_note)
            context.append(next_note)

        return generated_response